name: Check OS Version Updates

on:
  schedule:
    - cron: '0 */6 * * *'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    env:
      EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build and Run
        run: mvn compile exec:java -Dexec.mainClass="com.example.versionchecker.VersionChecker"

      - name: Commit version_state.json if changed
        run: |
            git config user.name "github-actions"
            git config user.email "github-actions@github.com"
            git add src/main/resources/version_state.json
            git diff --cached --quiet || git commit -m "⬆️ Update version_state.json via GitHub Actions"
            git push origin main  
